Repository KronicDeth/intellij-elixir, pull requests merged in 2018-08, with the labels that each got.

#1188 Show ... when Dbgi has no module name
  src/org/elixir_lang/beam/chunk/debug_info/v1/erl_abstract_code/abstract_code_compiler_options/abstract_code/Panel.kt
Labels: Kind:Bug

#1189 Don't assume callDefinitionClause is non-null
  src/org/elixir_lang/psi/impl/PresentationImpl.kt
Labels: Kind:Bug

#1190 Don't assume part of list access expression is QuotableKeywordPair
  src/org/elixir_lang/psi/ElementDescriptionProvider.kt
Labels: Kind:Bug

#1191 Don't assume parent of keywords is a list
  src/org/elixir_lang/psi/ElementDescriptionProvider.kt
Labels: Kind:Bug

#1192 Add all OTP 21 opcodes
  src/org/elixir_lang/beam/chunk/code/operation/Code.kt
Labels: Kind:Enhancement

#1203 Elixir 1.7 debugger compatibility
  resources/debugger/lib/intellij_elixir/debugger/server.ex
  src/org/elixir_lang/debugger/node/Binding.kt
Labels: Kind:Enhancement

#1208 Stop TerminalExecutionConole double echoing input in 2018.2 and 2018.2.1
  .travis.yml
  gradle.properties
  src/org/elixir_lang/distillery/State.kt
  src/org/elixir_lang/iex/State.kt
  src/org/elixir_lang/iex/mix/State.kt
  src/org/elixir_lang/run/PendingTasksRunner.java
  src/org/elixir_lang/run/TerminalExecutionConsole.java
Labels: Kind:Bug, Kind:Enhancement

#1210 Check parent of Pipe for enclosing macro call
  src/org/elixir_lang/psi/impl/PsiElementImpl.kt
  testData/org/elixir_lang/navigation/goto_symbol_contributor/issue_1141.ex
  tests/org/elixir_lang/navigation/GotoSymbolContributorTest.java
Labels: Kind:Bug, Kind:Enhancement

#1213 Treat EEx tag the same as StabBody for use scope
  CHANGELOG.md
  resources/META-INF/changelog.html
  src/org/elixir_lang/reference/Callable.kt
Labels: Kind:Bug

#1215 Filter directories of homePath lib to find apps
  jps-shared/src/org/elixir_lang/jps/HomePath.java
Labels: Kind:Bug

#1216 Remove assertion that a qualified alias has 3 children
  src/org/elixir_lang/psi/scope/Module.kt
Labels: Kind:Bug

#1217 Improve error logging for unexpected element class unaliased name down
  src/org/elixir_lang/reference/module/UnaliasedName.kt
Labels: Kind:Bug

#1168 Switch out the path separator on Windows
  src/org/elixir_lang/ElixirModules.kt
Labels: Kind:Bug

#1223 Convert mix and mix test run configurations to new format
  resources/META-INF/plugin.xml
  src/org/elixir_lang/exunit/Configuration.kt
  src/org/elixir_lang/run/conversion/Converter.kt
  src/org/elixir_lang/run/conversion/Provider.kt
  src/org/elixir_lang/run/conversion/RunConfiguration.kt
Labels: Kind:Enhancement

#1233 Look above `Enum.reduce` for enclosing macro call
  src/org/elixir_lang/psi/impl/PsiElementImpl.kt
  testData/org/elixir_lang/navigation/goto_symbol_contributor/issue_1228.ex
  tests/org/elixir_lang/navigation/GotoSymbolContributorTest.java
Labels: Kind:Bug, Kind:Enhancement

#1234 Add Facet SDK as External Library to re-enable indexing
  resources/META-INF/plugin.xml
  src/org/elixir_lang/facet/configurable/Project.kt
  src/org/elixir_lang/facet/external_library/conversion/Converter.kt
  src/org/elixir_lang/facet/external_library/conversion/ModuleSettings.kt
  src/org/elixir_lang/facet/external_library/conversion/Provider.kt
  src/org/elixir_lang/facet/sdks/Configurable.kt
Labels: Kind:Bug

#1239 Add pluginIcon for IntelliJ IDEA 2018.3 compatbility
  resources/META-INF/pluginIcon.svg
Labels: Kind:Enhancement
