Repository KronicDeth/intellij-elixir, pull requests merged in 2018-09, with the labels that each got.

#1244 Run createLibrary inside runWriteAction
  src/org/elixir_lang/facet/external_library/conversion/Converter.kt
  src/org/elixir_lang/facet/sdks/Configurable.kt
  tests/org/elixir_lang/mix/importWizard/MixProjectImportBuilderTest.java
Labels: Kind:Bug

#1245 Improve contribution guidelines
  CONTRIBUTING.md
Labels: Kind:Bug

#1246 Resolve unqualified bracket operation identifiers to variable and 0-arity calls
  gen/org/elixir_lang/psi/ElixirIdentifier.java
  gen/org/elixir_lang/psi/impl/ElixirIdentifierImpl.java
  src/org/elixir_lang/Elixir.bnf
  src/org/elixir_lang/annotator/Callable.kt
  src/org/elixir_lang/psi/impl/ElixirIdentifierImpl.kt
  src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
  src/org/elixir_lang/psi/scope/Identifier.kt
  src/org/elixir_lang/psi/scope/call_definition_clause/Variants.kt
  src/org/elixir_lang/reference/Identifier.kt
  src/org/elixir_lang/reference/resolver/Identifier.kt
Labels: Kind:Bug

#1248 Don't show decompiled in Go To Symbol or Declaration if source exists
  gradle.properties
  src/org/elixir_lang/navigation/GotoSymbolContributor.kt
  src/org/elixir_lang/navigation/SourcePreferredItems.kt
  src/org/elixir_lang/reference/resolver/Module.kt
  src/org/elixir_lang/structure_view/element/CallDefinitionClause.kt
  src/org/elixir_lang/structure_view/element/CallDefinitionHead.kt
  src/org/elixir_lang/structure_view/element/Quote.java
  src/org/elixir_lang/structure_view/element/modular/Quote.java
  tests/org/elixir_lang/navigation/GotoSymbolContributorTest.java
Labels: Kind:Bug, Kind:Incompatible Changes

#1249 Prefer source over decompiled for ResolveResultOrderedSet
  src/org/elixir_lang/navigation/SourcePreferredItems.kt
  src/org/elixir_lang/psi/scope/ResolveResultOrderedSet.kt
  src/org/elixir_lang/reference/resolver/Module.kt
Labels: Kind:Bug

#1255 Go to declaration through use
  src/org/elixir_lang/TargetElementEvaluator.kt
  src/org/elixir_lang/UsageTypeProvider.kt
  src/org/elixir_lang/annotator/Callable.kt
  src/org/elixir_lang/annotator/ModuleAttribute.java
  src/org/elixir_lang/annotator/Parameter.java
  src/org/elixir_lang/code_insight/completion/provider/CallDefinitionClause.kt
  src/org/elixir_lang/code_insight/line_marker_provider/CallDefinition.kt
  src/org/elixir_lang/code_insight/lookup/element_renderer/CallDefinitionClause.java
  src/org/elixir_lang/find_usages/handler/Call.kt
  src/org/elixir_lang/mix/TestFinder.java
  src/org/elixir_lang/mix/importWizard/ImportedOtpApp.kt
  src/org/elixir_lang/navigation/GotoSymbolContributor.kt
  src/org/elixir_lang/psi/CallDefinitionClause.kt
  src/org/elixir_lang/psi/ElementDescriptionProvider.kt
  src/org/elixir_lang/psi/Import.kt
  src/org/elixir_lang/psi/Modular.kt
  src/org/elixir_lang/psi/QuoteMacro.kt
  src/org/elixir_lang/psi/Use.kt
  src/org/elixir_lang/psi/Using.kt
  src/org/elixir_lang/psi/__MODULE__.kt
  src/org/elixir_lang/psi/__module__/PsiScopeProcessor.kt
  src/org/elixir_lang/psi/__module__/Reference.kt
  src/org/elixir_lang/psi/__module__/Resolver.kt
  src/org/elixir_lang/psi/call/name/Function.java
  src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
  src/org/elixir_lang/psi/impl/PresentationImpl.kt
  src/org/elixir_lang/psi/impl/ProcessDeclarationsImpl.kt
  src/org/elixir_lang/psi/impl/PsiElementImpl.kt
  src/org/elixir_lang/psi/impl/PsiNameIdentifierOwnerImpl.kt
  src/org/elixir_lang/psi/impl/UnqualifiedNoParenthesesCallImpl.kt
  src/org/elixir_lang/psi/impl/call/CallImpl.kt
  src/org/elixir_lang/psi/impl/call/qualification/QualifiedImpl.kt
  src/org/elixir_lang/psi/impl/declarations/UseScopeImpl.kt
  src/org/elixir_lang/psi/scope/CallDefinitionClause.java
  src/org/elixir_lang/psi/scope/CallDefinitionClause.kt
  src/org/elixir_lang/psi/scope/Variable.java
  src/org/elixir_lang/psi/scope/call_definition_clause/ArityInterval.kt
  src/org/elixir_lang/psi/scope/call_definition_clause/MultiResolve.kt
  src/org/elixir_lang/psi/stub/type/call/Stub.java
  src/org/elixir_lang/reference/Callable.kt
  src/org/elixir_lang/reference/resolver/CallDefinitionClause.kt
  src/org/elixir_lang/structure_view/Model.java
  src/org/elixir_lang/structure_view/element/CallDefinition.kt
  src/org/elixir_lang/structure_view/element/CallDefinitionClause.kt
  src/org/elixir_lang/structure_view/element/File.java
  src/org/elixir_lang/structure_view/element/Quote.java
  src/org/elixir_lang/structure_view/element/Use.java
  src/org/elixir_lang/structure_view/element/call_definition_by_name_arity/TreeElementList.kt
  src/org/elixir_lang/structure_view/element/modular/Module.kt
  src/org/elixir_lang/structure_view/node_provider/Used.kt
  tests/org/elixir_lang/code_insight/lookup/element_renderer/CallDefinitionClauseTest.java
  tests/org/elixir_lang/psi/ImportTest.java
  tests/org/elixir_lang/reference/callable/Issue354Test.java
  tests/org/elixir_lang/reference/callable/Issue463Test.java
  tests/org/elixir_lang/reference/callable/Issue480Test.java
  tests/org/elixir_lang/structure_view/element/CallDefinitionHeadTest.java
Labels: Kind:Enhancement

#1272 Separate dependencies out of project sources into non-project sources and External Libraries
  CHANGELOG.md
  resources/META-INF/intellij-erlang-plugin.xml
  resources/META-INF/plugin.xml
  resources/META-INF/rich-platform-plugin.xml
  resources/icons/library/mix.svg
  resources/icons/library/mix@2x.svg
  resources/icons/library/mix@3x.svg
  src/org/elixir_lang/DepsWatcher.kt
  src/org/elixir_lang/PackageManager.kt
  src/org/elixir_lang/mix/Dep.kt
  src/org/elixir_lang/mix/DepGatherer.kt
  src/org/elixir_lang/mix/Icons.kt
  src/org/elixir_lang/mix/PackageManager.kt
  src/org/elixir_lang/mix/Watcher.kt
  src/org/elixir_lang/mix/importWizard/MixProjectImportBuilder.java
  src/org/elixir_lang/mix/importWizard/MixProjectOpenProcessor.java
  src/org/elixir_lang/mix/library/Kind.kt
  src/org/elixir_lang/mix/library/Type.kt
  src/org/elixir_lang/mix/project/OpenProcessor.kt
  src/org/elixir_lang/mix/project/_import/Builder.kt
  src/org/elixir_lang/mix/project/_import/OtpApp.kt
  src/org/elixir_lang/mix/project/_import/Provider.java
  src/org/elixir_lang/mix/project/_import/step/Root.form
  src/org/elixir_lang/mix/project/_import/step/Root.java
  src/org/elixir_lang/mix/project/_import/step/SelectOtpApps.java
  src/org/elixir_lang/module/ElixirProjectStructureDetector.java
  src/org/elixir_lang/package_manager/DepGatherer.kt
  src/org/elixir_lang/package_manager/VirtualFile.kt
  src/org/elixir_lang/psi/impl/PsiElementImpl.kt
  src/org/elixir_lang/psi/impl/QuotableImpl.kt
  src/org/elixir_lang/psi/impl/QuotableKeywordPairImpl.kt
  src/org/elixir_lang/psi/impl/call/CallImpl.kt
  src/org/elixir_lang/rebar3/DepGatherer.kt
  src/org/elixir_lang/rebar3/PackageManager.kt
Labels: Kind:Enhancement, Kind:Incompatible Changes

#1275 Go To Module with Go To Class action
  resources/META-INF/plugin.xml
  src/org/elixir_lang/annotator/Module.java
  src/org/elixir_lang/beam/psi/impl/CallDefinitionStubImpl.java
  src/org/elixir_lang/beam/psi/impl/CallDefinitionStubImpl.kt
  src/org/elixir_lang/beam/psi/impl/ModuleStubImpl.java
  src/org/elixir_lang/mix/Dep.kt
  src/org/elixir_lang/navigation/ChooseByNameContributor.kt
  src/org/elixir_lang/navigation/GotoClassContributor.kt
  src/org/elixir_lang/navigation/GotoSymbolContributor.kt
  src/org/elixir_lang/psi/Definition.kt
  src/org/elixir_lang/psi/stub/call/Stub.java
  src/org/elixir_lang/psi/stub/call/Stubbic.java
  src/org/elixir_lang/psi/stub/call/Stubbic.kt
  src/org/elixir_lang/psi/stub/index/ModularName.kt
  src/org/elixir_lang/psi/stub/type/Named.java
  src/org/elixir_lang/psi/stub/type/Named.kt
Labels: Kind:Enhancement

#1277 Don't inclue null useCall as __MODULE__ dependency
  src/org/elixir_lang/psi/__MODULE__.kt
Labels: Kind:Bug

#1279 Wrap LibraryTable and Library writes in write action
  src/org/elixir_lang/facet/sdks/Configurable.kt
Labels: Kind:Bug

#1280 Handle commit and overrride for Mix.Dep
  src/org/elixir_lang/mix/Dep.kt
Labels: Kind:Enhancement

#1282 Check if Mix.Dep has already been seen to prevent recursive loops
  src/org/elixir_lang/mix/Watcher.kt
Labels: Kind:Bug

#1283 Add .eex to .ex and .exs for accepted file extensions in stacktraces
  src/org/elixir_lang/console/FileReferenceFilter.java
Labels: Kind:Bug

#1285 alias __MODULE__ and alias M, as: N support
  build.gradle
  src/org/elixir_lang/psi/__module__/AliasPresentation.kt
  src/org/elixir_lang/psi/impl/PresentationImpl.kt
  src/org/elixir_lang/psi/impl/qualifiable_alias/ItemPresentation.kt
  src/org/elixir_lang/psi/scope/Module.kt
  src/org/elixir_lang/psi/scope/module/MultiResolve.kt
  src/org/elixir_lang/reference/module/UnaliasedName.kt
  tests/org/elixir_lang/reference/module/AsTest.java
Labels: Kind:Enhancement
