Repository KronicDeth/intellij-elixir, pull requests merged in 2019-10, with the labels that each got.

#1600 Parameter info
  CHANGELOG.md
  README.md
  gradle.properties
  resources/META-INF/changelog.html
  resources/META-INF/plugin.xml
  screenshots/features/Show Parameters.png
  src/org/elixir_lang/code_insight/ParameterInfo.kt
Labels: Kind:Enhancement

#1607 Fix "Unknown Elixir version" in settings
  src/org/elixir_lang/sdk/ProcessOutput.java
Labels: Kind:Bug

#1608 Don't use parentheses in Elixir version eval
  CHANGELOG.md
  resources/META-INF/changelog.html
  src/org/elixir_lang/sdk/elixir/Type.java
Labels: Kind:Bug, Operating System:Windows
