Repository KronicDeth/intellij-elixir, pull requests merged in 2021-02, with the labels that each got.

#1899 Don't return null left or right infix operands in `Infix.primaryArguments`
  .github/workflows/release.yml
  .github/workflows/test.yml
  CHANGELOG.md
  resources/META-INF/changelog.html
  src/org/elixir_lang/psi/impl/call/CallImpl.kt
Labels: Kind:Bug, Kind:Enhancement

#1902 ASDF SDK
  CHANGELOG.md
  jps-shared/src/org/elixir_lang/jps/HomePath.java
  resources/META-INF/changelog.html
  src/org/elixir_lang/espec/configuration/Producer.kt
  src/org/elixir_lang/exunit/Configuration.kt
  src/org/elixir_lang/exunit/configuration/Producer.kt
  src/org/elixir_lang/facet/Configuration.kt
  src/org/elixir_lang/facet/Type.kt
  src/org/elixir_lang/facet/sdks/elixir/Configurable.kt
  src/org/elixir_lang/facet/sdks/erlang/Configurable.kt
  src/org/elixir_lang/inspection/SetupSDKNotificationProvider.kt
  src/org/elixir_lang/mix/State.kt
  src/org/elixir_lang/mix/project/_import/Builder.kt
  src/org/elixir_lang/psi/impl/ParentImpl.kt
  src/org/elixir_lang/psi/impl/QuotableArgumentsImpl.kt
  src/org/elixir_lang/psi/impl/QuotableImpl.kt
  src/org/elixir_lang/sdk/elixir/Type.java
  src/org/elixir_lang/sdk/elixir/Type.kt
  src/org/elixir_lang/sdk/erlang/Type.java
  src/org/elixir_lang/sdk/erlang_dependent/Type.java
  tests/org/elixir_lang/sdk/elixir/TypeTest.java
Labels: Kind:Bug, Kind:Enhancement, Version Manager:asdf

#1821 Experimental "mix dialyzer" support
  CHANGELOG.md
  README.md
  resources/META-INF/changelog.html
  resources/META-INF/plugin.xml
  resources/inspectionDescriptions/Dialyzer.html
  screenshots/features/dialyzer/inspection/batch_mode/Code Highlighting.png
  screenshots/features/dialyzer/inspection/batch_mode/Individual Entry.png
  screenshots/features/dialyzer/inspection/batch_mode/Run Dialyzer based inspections (Elixir) Whole Project.png
  src/org/elixir_lang/dialyzer/inspection/Global.kt
  src/org/elixir_lang/dialyzer/service/Configurable.form
  src/org/elixir_lang/dialyzer/service/Configurable.kt
  src/org/elixir_lang/dialyzer/service/DialyzerOutputParsing.kt
  src/org/elixir_lang/dialyzer/service/DialyzerService.kt
  src/org/elixir_lang/dialyzer/service/DialyzerServiceImpl.kt
  src/org/elixir_lang/dialyzer/service/State.kt
  src/org/elixir_lang/run/Configuration.kt
Labels: Kind:Enhancement
