Repository KronicDeth/intellij-elixir, pull requests merged in 2022-05, with the labels that each got.

#2633 Fix Deprecate Warning fixes that broke small IDEs
  CHANGELOG.md
  build.gradle
  resources/META-INF/changelog.html
  src/org/elixir_lang/facet/configurable/Project.kt
  src/org/elixir_lang/notification/setup_sdk/Listener.kt
  src/org/elixir_lang/notification/setup_sdk/Provider.kt
  src/org/elixir_lang/sdk/erlang_dependent/SdkAdditionalData.java
Labels: Kind:Bug, IDE:Rubymine

#2637 Protect from `null` `containingFile` when fetching docs
  CHANGELOG.md
  gradle.properties
  resources/META-INF/changelog.html
  src/org/elixir_lang/documentation/ElixirDocumentationProvider.kt
Labels: Kind:Bug

#2639 Show notification if $HOME_PATH/lib does not exist
  CHANGELOG.md
  jps-shared/src/org/elixir_lang/jps/HomePath.java
  resources/META-INF/changelog.html
Labels: Kind:Bug

#2640 Ignore tuples as type restrictions that occur during typing
  CHANGELOG.md
  resources/META-INF/changelog.html
  src/org/elixir_lang/psi/impl/ProcessDeclarationsImpl.kt
Labels: Kind:Bug

#2641 Catch AlreadyDisposedException when trying to find module for PsiElement
  CHANGELOG.md
  resources/META-INF/changelog.html
  src/org/elixir_lang/sdk/elixir/Type.kt
Labels: Kind:Bug

#2642 Ignore `()` as a type parameter as it occurs during typing.
  CHANGELOG.md
  resources/META-INF/changelog.html
  src/org/elixir_lang/annotator/ModuleAttribute.kt
Labels: Kind:Bug

#2643 Default to the variable color if the specific type foreground is null
  CHANGELOG.md
  resources/META-INF/changelog.html
  src/org/elixir_lang/code_insight/lookup/element_renderer/Variable.java
Labels: Kind:Bug

#2644 Log unknown element for fetching docs from BEAM file
  CHANGELOG.md
  resources/META-INF/changelog.html
  src/org/elixir_lang/documentation/BeamDocsHelper.kt
Labels: Kind:Bug

#2645 Look above CallDefinitionImpl for Type scope processing
  CHANGELOG.md
  resources/META-INF/changelog.html
  src/org/elixir_lang/psi/scope/Type.kt
Labels: Kind:Bug

#2671 Restore Credo Global Inspection
  CHANGELOG.md
  README.md
  resources/META-INF/changelog.html
  resources/META-INF/plugin.xml
  screenshots/features/credo/external_annotator/Explanation.png
  screenshots/features/credo/external_annotator/Warning Annotations.png
  src/org/elixir_lang/credo/Action.kt
  src/org/elixir_lang/credo/Annotator.java
  src/org/elixir_lang/credo/Configurable.form
  src/org/elixir_lang/credo/Configurable.java
  src/org/elixir_lang/credo/Service.kt
  src/org/elixir_lang/credo/State.java
  src/org/elixir_lang/credo/State.kt
  src/org/elixir_lang/credo/inspection_tool/Global.kt
  src/org/elixir_lang/credo/inspection_tool/Local.kt
  src/org/elixir_lang/credo/state/Env.kt
  src/org/elixir_lang/credo/state/EnvironmentVariablesData.kt
  src/org/elixir_lang/notification/setup_sdk/Action.kt
Labels: Kind:Bug, Feature:Credo

#2672 Fix ancestorTypeSpec when typing <variable>.<tuple>
  CHANGELOG.md
  resources/META-INF/changelog.html
  src/org/elixir_lang/psi/scope/Type.kt
Labels: Kind:Bug

#2673 Fix Find Usages that resolve to compiled types
  CHANGELOG.md
  resources/META-INF/changelog.html
  src/org/elixir_lang/annotator/ModuleAttribute.kt
  src/org/elixir_lang/beam/psi/impl/ModuleImpl.kt
  src/org/elixir_lang/errorreport/Logger.kt
  src/org/elixir_lang/github/issues/create/Request.kt
  src/org/elixir_lang/navigation/item_presentation/Type.java
  src/org/elixir_lang/psi/ElementDescriptionProvider.kt
  src/org/elixir_lang/type/Visibility.kt
Labels: Kind:Bug, Kind:Enhancement

#2674 Catch `RuntimeException` if `rootProvider` is already disposed
  CHANGELOG.md
  resources/META-INF/changelog.html
  src/org/elixir_lang/Erl.kt
Labels: Kind:Bug

#2675 Ignore dot calls during user typing when highlighting types
  CHANGELOG.md
  resources/META-INF/changelog.html
  src/org/elixir_lang/annotator/ModuleAttribute.kt
Labels: Kind:Bug

#2679 2677
  .tool-versions
  CHANGELOG.md
  resources/META-INF/changelog.html
  src/org/elixir_lang/find_usages/Provider.kt
  src/org/elixir_lang/psi/ElementDescriptionProvider.kt
Labels: Kind:Bug

#2680 Highlight CallDefinitionImpl as predefined if it is in Kernel or Kernel.SpecialForms
  CHANGELOG.md
  resources/META-INF/changelog.html
  src/org/elixir_lang/annotator/Callable.kt
Labels: Kind:Bug

#2681 Fix Elixir SDK persistence in Small IDEs
  CHANGELOG.md
  resources/META-INF/changelog.html
  src/org/elixir_lang/Facet.java
  src/org/elixir_lang/Facet.kt
  src/org/elixir_lang/facet/Configuration.kt
  src/org/elixir_lang/facet/Type.kt
  src/org/elixir_lang/facet/configurable/Project.kt
  src/org/elixir_lang/sdk/elixir/Type.kt
Labels: Kind:Bug

#2687 New Projects > Language > Elixir in IntelliJ 2022
  CHANGELOG.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  resources/META-INF/changelog.html
  resources/META-INF/rich-platform-plugin.xml
  src/org/elixir_lang/Elixir.kt
  src/org/elixir_lang/Erl.kt
  src/org/elixir_lang/NewProjectWizard.kt
  src/org/elixir_lang/module/ElixirModuleBuilder.java
  src/org/elixir_lang/module/ElixirModuleBuilder.kt
  src/org/elixir_lang/new_project_wizard/Data.kt
  src/org/elixir_lang/new_project_wizard/Step.kt
Labels: Kind:Bug, Kind:Enhancement

#2578 feat: add mix fmt external format processor
  CHANGELOG.md
  README.md
  resources/META-INF/changelog.html
  resources/META-INF/plugin.xml
  src/org/elixir_lang/code_style/CodeStyleSettings.java
  src/org/elixir_lang/formatter/MixFormatExternalFormatProcessor.kt
  src/org/elixir_lang/formatter/settings/CodeStyleSettingsProvider.java
  src/org/elixir_lang/formatter/settings/ElixirCodeStyleMainPanel.kt
  src/org/elixir_lang/formatter/settings/LanguageCodeStyleSettingsProvider.kt
  src/org/elixir_lang/formatter/settings/MixFormatPanel.kt
  tests/org/elixir_lang/FormattingTest.java
Labels: Kind:Enhancement

#2695 Restrict UsageTargetProvider to ElixirFiles
  CHANGELOG.md
  resources/META-INF/changelog.html
  src/org/elixir_lang/UsageTargetProvider.kt
Labels: Kind:Bug

#2697 Support Debugger in Elixir 1.13.0
  CHANGELOG.md
  resources/META-INF/changelog.html
  resources/debugger/lib/intellij_elixir/debugger/server.ex
  src/org/elixir_lang/espec/Configuration.kt
  src/org/elixir_lang/exunit/Configuration.kt
Labels: Kind:Bug, Kind:Enhancement
